
source ‘https://cdn.cocoapods.org/’

use_frameworks!
platform :ios, '12.0'

target 'Kommunicate_Example' do
  pod 'Kommunicate', :path => '../'
  target 'Kommunicate_Tests' do
    inherit! :search_paths
    pod 'ApplozicSwift', :git => 'https://github.com/Sathyan-Elangovan/KommunicateChatUI-iOS-SDK.git', :branch => 'CM_709_iOS_Listner’, :commit => '1653c90774def6eb95166c74b6e2359c245f6d32'

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble'
    pod 'Quick'
    pod 'Nimble-Snapshots'
  end
end
target 'Kommunicate_ExampleUITests' do
  inherit! :search_paths
  pod 'Kommunicate', :path => '../'
end
