source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
platform :ios, '10.0'

target 'Kommunicate_Example' do
  pod 'Kommunicate', :path => '../'
  target 'Kommunicate_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble'
    pod 'Quick'
    pod 'Nimble-Snapshots'
    pod 'ApplozicSwift', :git => 'https://github.com/AppLozic/ApplozicSwift.git', :branch => 'CM-516'
  end
end
target 'Kommunicate_ExampleUITests' do
  inherit! :search_paths
  pod 'Kommunicate', :path => '../'
end
