name: iOS Automation Test Workflow

on:
  push:
    branches:
      - dev # Run the workflow on pushes to the dev branch
  pull_request:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Xcode
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2.0' # Replace with the Xcode version you need

      # Step 3: Install dependencies (if using CocoaPods or Carthage)
      - name: Install Dependencies
        run: |
          pod install --project-directory=Example


      - name: Append new key in info.plist in Example
        run: |
          PLIST_PATH="Example/Kommunicate/Info.plist"
          KEY="KOMMUNICATE_APP_ID"
          VALUE="${{ secrets.KOMMUNICATE_APP_ID }}"
          /usr/libexec/PlistBuddy -c "Set :$KEY $VALUE" "$PLIST_PATH" || \
          /usr/libexec/PlistBuddy -c "Add :$KEY string $VALUE" "$PLIST_PATH"
          cat "$PLIST_PATH"

      - name: Append new key in info.plist in Tests
        run: |
          PLIST_PATH="Example/Tests/Info.plist"
          KEY="KOMMUNICATE_APP_ID"
          VALUE="${{ secrets.KOMMUNICATE_APP_ID }}"
          /usr/libexec/PlistBuddy -c "Set :$KEY $VALUE" "$PLIST_PATH" || \
          /usr/libexec/PlistBuddy -c "Add :$KEY string $VALUE" "$PLIST_PATH"
          cat "$PLIST_PATH"

      - name: Append new key in info.plist in UI Tests
        run: |
          PLIST_PATH="Example/Kommunicate_ExampleUITests/Info.plist"
          KEY="KOMMUNICATE_APP_ID"
          VALUE="${{ secrets.KOMMUNICATE_APP_ID }}"
          /usr/libexec/PlistBuddy -c "Set :$KEY $VALUE" "$PLIST_PATH" || \
          /usr/libexec/PlistBuddy -c "Add :$KEY string $VALUE" "$PLIST_PATH"
          cat "$PLIST_PATH"

      # Step 4: Run Tests
      - name: Run XCTest
        env:
          KOMMUNICATE_APP_ID: ${{ secrets.KOMMUNICATE_APP_ID }}
        run: |
          xcodebuild test \
            -workspace Example/Kommunicate.xcworkspace \
            -scheme Kommunicate_Example \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.2' \
            CODE_SIGNING_ALLOWED=NO \ xcpretty --test --color
            CODE_SIGNING_REQUIRED=NO \
            -enableCodeCoverage YES
            -derivedDataPath ./DerivedData

      # Step 6 (Optional): Debug Environment Variables (Do not expose secrets in logs)
      - name: Debug Environment Variables
        run: |
          echo "Environment variables set successfully."
