name: iOS Automation Test Workflow

on:
  push:
    branches:
      - dev # Run the workflow on pushes to the main branch
  pull_request:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-latest

    steps:
    # Checkout the code
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Set up Xcode
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.1.0' # Replace with the Xcode version you need

    # Install dependencies (if using CocoaPods or Carthage)
    - name: Install Dependencies
      run: |
        pod install --project-directory=Example

    # Set environment variable for the secret
    - name: Set Environment Variable
      run: echo "APP_ID=${{ secrets.APP_ID }}" >> $GITHUB_ENV

    - name: Use Environment Variable in Script
      run: |
        if [ -n "$APP_ID" ]; then
          echo "App ID is set."
        else
          echo "App ID is missing."
          exit 1
        fi

    # Run Tests
    - name: Run XCTest
      env:
        APP_ID: ${{ env.APP_ID }}
      run: |
        xcodebuild test \
          -workspace Example/Kommunicate.xcworkspace \
          -scheme Kommunicate_Example \
          -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.1' \
          CODE_SIGNING_ALLOWED=NO \
          -enableCodeCoverage YES
          APP_ID=$APP_ID
